import { readdir, readFile, writeFile, mkdir, stat } from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";
import type { BundleData, PageReview } from "../types";

const viewerRoot = resolve(import.meta.dir, "..");
const repoRoot = viewerRoot;
const legacyWorkspaceRoot = resolve(viewerRoot, "..");
const sourceDir = process.env.ABSTRACTIONS_DIR
  ? resolve(process.env.ABSTRACTIONS_DIR)
  : join(viewerRoot, "todo", "abstractions");
const targetFile = join(viewerRoot, "data-bundle.ts");
const localCachePrefix = join(repoRoot, ".cache");
const legacyCachePrefix = join(legacyWorkspaceRoot, ".cache");

const pageReviews: PageReview[] = [];
const parseFailures: BundleData["parseFailures"] = [];

for (const file of (await readdir(sourceDir)).filter((name) => name.endsWith(".json")).sort()) {
  const filePath = join(sourceDir, file);
  try {
    const [text, st] = await Promise.all([readFile(filePath, "utf8"), stat(filePath)]);
    const parsed = JSON.parse(text);
    for (const review of parsed.pageReviews ?? []) {
      pageReviews.push({
        ...review,
        _sourcePath: filePath,
        _mtimeMs: st.mtimeMs,
        findings: Array.isArray(review.findings) ? review.findings : [],
      });
    }
  } catch (error) {
    parseFailures.push({ file: basename(filePath), error: (error as Error).message });
  }
}

pageReviews.sort((a, b) => a.pageLabel.localeCompare(b.pageLabel));

const totals: BundleData["totals"] = {
  pagesReviewed: pageReviews.length,
  pagesWithFindings: 0,
  pagesWithNoActionableFindings: 0,
  incompleteOrUnparseable: 0,
  findings: 0,
  byPriority: {},
  byKind: {},
  byCategory: {},
  byStatus: {},
};

for (const review of pageReviews) {
  totals.byStatus[review.status] = (totals.byStatus[review.status] ?? 0) + 1;
  if (review.status === "has-findings") totals.pagesWithFindings += 1;
  if (review.status === "no-actionable-findings") totals.pagesWithNoActionableFindings += 1;
  if (review.status === "incomplete-or-unparseable") totals.incompleteOrUnparseable += 1;
  for (const finding of review.findings ?? []) {
    totals.findings += 1;
    const priority = finding.priority ?? "—";
    const kind = finding.kind ?? "—";
    const category = finding.category ?? "—";
    totals.byPriority[priority] = (totals.byPriority[priority] ?? 0) + 1;
    totals.byKind[kind] = (totals.byKind[kind] ?? 0) + 1;
    totals.byCategory[category] = (totals.byCategory[category] ?? 0) + 1;
  }
}

const payload: BundleData = {
  generatedAt: new Date().toISOString(),
  sourceDir,
  parseFailures,
  pageReviews,
  totals,
};
const publicPayload = sanitizePublicValue(payload) as BundleData;

await mkdir(dirname(targetFile), { recursive: true });
await writeFile(
  targetFile,
  `// AUTO-GENERATED by scripts/build-data.ts — do not edit by hand
import type { BundleData } from "./types";
export const bundle: BundleData = ${JSON.stringify(publicPayload, null, 2)} as BundleData;
`,
);

console.log(`bundled ${pageReviews.length} page review(s), ${totals.findings} finding(s) from ${sourceDir} -> ${targetFile}`);

function sanitizePublicValue(value: unknown): unknown {
  if (typeof value === "string") {
    return value
      .split(`${localCachePrefix}/`).join("")
      .split(localCachePrefix).join("")
      .split(`${legacyCachePrefix}/`).join("")
      .split(legacyCachePrefix).join("")
      .split(`${repoRoot}/`).join("")
      .split(repoRoot).join("")
      .split(`${legacyWorkspaceRoot}/`).join("")
      .split(legacyWorkspaceRoot).join("");
  }
  if (Array.isArray(value)) return value.map(sanitizePublicValue);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value)
        .map(([key, nested]) => [key, sanitizePublicValue(nested)]),
    );
  }
  return value;
}
